#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function help {
    echo "Availible commands are:"
    echo "   pminer        Software propagation study"
    echo "   smf           Project and mutation managing"
    echo "   softminer     Software graphs tools"
    echo "   softwearn     Learning versions of tools"
    exit
}

if [ "$#" -eq 0 ]; then
    echo "Illegal number of parameters"
    help
    exit
fi

case "$1" in

pminer)
    script="bin/pminer"
    ;;
smf)
    script="bin/smf"
    ;;
softminer)
    script="bin/softminer"
    ;;
softwearn)
    script="bin/softwearn"
    ;;
*)
    echo "Unknown command $1"
    exit
    ;;
esac

shift
bash $DIR/$script "$@"
